[package]
name = "check_att"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
exitfailure = "0.5.1"
reqwest = { version = "0.11.14", features = ["json"] }
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
structopt = "0.3.26"
tokio = { version = "1.24.2", features = ["full"] }
